spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 183438077047-c7gmo7io280sk52mhatjrcgfctocn7gj.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-name: Google
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
server:
  servlet:
    session:
      timeout: 30m  # Session timeout of 30 minutes

